[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dem = "6e8f8Gbnq1qd5ApwXTh5gJq6GEMWi1G1Kvz5TsakiT56"
mintr = "9r3XTs1andLuWwTkpuWsr8HvzG9Gi9mXc6MfeN5ePM6n"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
