[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_contract = "6zRvZSDvHbzXRS1zSuD3dZ6BCbaVqMJtUrorvwg7hG3Q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
